resolver: lts-16.12
packages:
- pact-db
- pact-web-server

extra-deps:
- yamlparse-applicative-0.1.0.2@sha256:bda91f2818c1b5b124963931cb7f9a4e5758d026c09713e9ae2234534062747d,2133
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid

- github: NorfairKing/validity
  commit: 466bb2f140e62cae0d4fe3770681c3d74e99cf40
  subdirs:
  - validity
  - validity-persistent
  - validity-time
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-uuid

- github: NorfairKing/safe-coloured-text
  commit: 7f157485e55528648a95edf3508a122b2e55779e
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 54b5d0bf59e5bdabd3be098780afee63fbbbf158
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-wai
    - sydtest-yesod

- github: NorfairKing/yesod-autoreload
  commit: 7135e864c0d4a48efeae473ee2761f5168946e58

- github: NorfairKing/autodocodec
  commit: 9880ec062f1166bdac50b8eb59c6dd010bc9af0c
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema

nix:
  enable: true
  packages: [ zlib ]
