resolver: lts-20.25
packages:
- oura
- pact-db
- pact-web-server

extra-deps:
- yamlparse-applicative-0.2.0.1
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d

- github: NorfairKing/typed-uuid
  commit: 00fbc7e0380ab2ff72e8fd02323e76f13b7d5b59
  subdirs:
    - typed-uuid
    - genvalidity-typed-uuid

- github: NorfairKing/validity
  commit: d88be911a7e2a84f6c089e9269aaed8d10a74acd
  subdirs:
  - validity
  - validity-aeson
  - validity-persistent
  - validity-time
  - genvalidity
  - genvalidity-bytestring
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-persistent
  - genvalidity-text
  - genvalidity-time
  - genvalidity-uuid

- github: NorfairKing/safe-coloured-text
  commit: 675cb01fce5f46718416d7746de5b856ed90a63f
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 130de92053c1c3d60a8f45d509210415ffbea530
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-wai
    - sydtest-yesod

- github: NorfairKing/yesod-autoreload
  commit: 796def9af50cd7b053c9fb4a065c55603d4a8399

- github: NorfairKing/autodocodec
  commit: 479390d82e4fb2a404c497d6b9a9fec1505b1e5e
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema

system-ghc: true
nix:
  enable: false
with-hpack: hpack
