resolver: lts-16.12
packages:
- pact-db
- pact-web-server

extra-deps:
- yamlparse-applicative-0.1.0.2@sha256:bda91f2818c1b5b124963931cb7f9a4e5758d026c09713e9ae2234534062747d,2133
- github: supki/envparse
  commit: de5944fb09e9d941fafa35c0f05446af348e7b4d

- github: NorfairKing/typed-uuid
  commit: ec82b82a545d06094ac355bd65a03f25f86c0a48
  subdirs:
    - typed-uuid

- github: NorfairKing/validity
  commit: bafcaf3799fa76edd5968923f6efde25085815f9
  subdirs:
  - validity-persistent
  - validity-time
  - genvalidity-sydtest
  - genvalidity-sydtest-aeson
  - genvalidity-sydtest-persistent
  - genvalidity-time

- github: NorfairKing/safe-coloured-text
  commit: 7f157485e55528648a95edf3508a122b2e55779e
  subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

- github: NorfairKing/sydtest
  commit: 9a4c6040db470a88172d36ffa8ce3e466b3cd827
  subdirs:
    - sydtest
    - sydtest-aeson
    - sydtest-discover
    - sydtest-persistent
    - sydtest-persistent-sqlite
    - sydtest-wai
    - sydtest-yesod

- github: NorfairKing/yesod-autoreload
  commit: 7135e864c0d4a48efeae473ee2761f5168946e58
