name:                pact-db
version:             0.0.0.0
github:              "CSVdB/pact-code"
license:             AllRightsReserved
author:              "Nick Van den Broeck"
maintainer:          "vandenbroeck@cs-vdb.com"
copyright:           "Copyright (c) 2021 PACT"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - blaze-markup
    - bytestring
    - either
    - jose
    - monad-logger
    - password
    - password-instances
    - persistent
    - persistent-sqlite
    - persistent-template
    - servant
    - servant-auth
    - servant-auth-server
    - servant-client-core
    - text
    - typed-uuid
    - uuid
    - validity
    - validity-bytestring
    - validity-persistent
    - validity-text
    - validity-uuid
    - yamlparse-applicative
    - yesod
