name:                pact-api-server
version:             0.0.0.0
github:              "CSVdB/pact-code"
license:             AllRightsReserved
author:              "PACT"
maintainer:          "vandenbroeck@cs-vdb.com"
copyright:           "Copyright (c) 2021 PACT"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - envparse
    - jose
    - monad-logger
    - mtl
    - optparse-applicative
    - pact-api
    - pact-db
    - password
    - password-instances
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - servant-auth-server
    - servant-server
    - text
    - time
    - validity
    - wai
    - wai-cors
    - wai-extra
    - warp
    - yaml
    - yamlparse-applicative

executables:
  pact-api-server:
    main: Main.hs
    source-dirs: app/
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    dependencies:
      - pact-api-server
