name:                pact-api-gen
version:             0.0.0.0
github:              "CSVdB/pact-code"
license:             AllRightsReserved
author:              "PACT"
maintainer:          "vandenbroeck@cs-vdb.com"
copyright:           "Copyright (c) 2021 PACT"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - genvalidity
    - genvalidity-text
    - pact-api
    - pact-db
    - text

tests:
  pact-api-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - genvalidity-hspec
    - hspec
    - pact-api
    - pact-api-gen
    - pact-db
