name:                oura
version:             0.0.0.0
github:              "CSVdB/pact-code"
license:             AllRightsReserved
author:              "Nick Van den Broeck"
maintainer:          "vandenbroeck@cs-vdb.com"
copyright:           "Copyright (c) 2023 PACT"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools: autoexporter
  dependencies:
  - aeson
  - containers
  - envparse
  - http-client
  - http-client-tls
  - microlens
  - monad-logger
  - optparse-applicative
  - pact-db
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - servant
  - servant-client
  - text
  - time
  - vector
  ghc-options:
  - -Wall
  - -Werror

executables:
  oura:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - oura

tests:
  oura-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -Wall
    - -Werror
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sydtest
