name:                pact-client
version:             0.0.0.0
github:              "CSVdB/pact-code"
license:             AllRightsReserved
author:              "PACT"
maintainer:          "vandenbroeck@cs-vdb.com"
copyright:           "Copyright (c) 2021 PACT"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - servant
    - servant-auth
    - servant-auth-client
    - servant-client
    - servant-client-core
    - text
    - validity
    - validity-text
    - pact-api
